/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthPendingRouteImport } from './routes/auth-pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as DashboardProviderRouteImport } from './routes/dashboard.provider'
import { Route as DashboardCustomerRouteImport } from './routes/dashboard.customer'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingRoute = AuthPendingRouteImport.update({
  id: '/auth-pending',
  path: '/auth-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProviderRoute = DashboardProviderRouteImport.update({
  id: '/dashboard/provider',
  path: '/dashboard/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/dashboard/customer',
  path: '/dashboard/customer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/auth-pending': typeof AuthPendingRoute
  '/book': typeof BookRoute
  '/services': typeof ServicesRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers/': typeof ProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/auth-pending': typeof AuthPendingRoute
  '/book': typeof BookRoute
  '/services': typeof ServicesRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers': typeof ProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/auth-pending': typeof AuthPendingRoute
  '/book': typeof BookRoute
  '/services': typeof ServicesRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers/': typeof ProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/auth-pending'
    | '/book'
    | '/services'
    | '/dashboard/customer'
    | '/dashboard/provider'
    | '/providers/$id'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/auth-pending'
    | '/book'
    | '/services'
    | '/dashboard/customer'
    | '/dashboard/provider'
    | '/providers/$id'
    | '/providers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/auth-pending'
    | '/book'
    | '/services'
    | '/dashboard/customer'
    | '/dashboard/provider'
    | '/providers/$id'
    | '/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  AuthPendingRoute: typeof AuthPendingRoute
  BookRoute: typeof BookRoute
  ServicesRoute: typeof ServicesRoute
  DashboardCustomerRoute: typeof DashboardCustomerRoute
  DashboardProviderRoute: typeof DashboardProviderRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-pending': {
      id: '/auth-pending'
      path: '/auth-pending'
      fullPath: '/auth-pending'
      preLoaderRoute: typeof AuthPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider': {
      id: '/dashboard/provider'
      path: '/dashboard/provider'
      fullPath: '/dashboard/provider'
      preLoaderRoute: typeof DashboardProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customer': {
      id: '/dashboard/customer'
      path: '/dashboard/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  AuthPendingRoute: AuthPendingRoute,
  BookRoute: BookRoute,
  ServicesRoute: ServicesRoute,
  DashboardCustomerRoute: DashboardCustomerRoute,
  DashboardProviderRoute: DashboardProviderRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
